"use strict";

const express = require("express");
const probe = require("../services/camera-probe");

module.exports = function createNetworkRouter(deps) {
  const { pool, authenticateToken, getEffectiveCompanyId, requirePermission } = deps;
  const router = express.Router();
  const companyOf = (req) => Number(getEffectiveCompanyId(req) || req.user?.company_id || 0);
  const tenantOf = (req) => req.user?.tenant_id || null;
  const perm = (key, action) => requirePermission ? requirePermission(key, action) : (_req, _res, next) => next();
  const text = (value, max = 255) => String(value ?? "").trim().slice(0, max);
  const CATEGORIES = new Set(["router","switch","access_point","firewall","server","nas","nvr","dvr","camera","printer","computer","phone","ups","other"]);
  const MAC = /^([0-9a-f]{2}[:-]){5}[0-9a-f]{2}$/i;

  async function owned(table, id, companyId) {
    if (!new Set(["network_sites","network_devices","users","warehouses"]).has(table)) throw new Error("Table interdite.");
    if (!id) return null;
    const companyColumn = table === "users" ? "company_id" : "company_id";
    return (await pool.query(`SELECT * FROM ${table} WHERE id=$1 AND ${companyColumn}=$2`,[Number(id),companyId])).rows[0]||null;
  }
  async function audit(req, action, entityType, entityId, detail="") {
    await pool.query(`INSERT INTO network_audit_logs (company_id,tenant_id,user_id,action,entity_type,entity_id,detail)
      VALUES ($1,$2,$3,$4,$5,$6,$7)`,[companyOf(req),tenantOf(req),req.user.id,action,entityType,entityId,text(detail,1000)]);
  }

  router.get("/network/dashboard",authenticateToken,perm("reseau","view"),async(req,res)=>{
    try{const companyId=companyOf(req);const [devices,incidents,maintenance,conflicts]=await Promise.all([
      pool.query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='online')::int AS online,
        COUNT(*) FILTER(WHERE status='offline')::int AS offline,COUNT(*) FILTER(WHERE status='unknown')::int AS unknown
        FROM network_devices WHERE company_id=$1`,[companyId]),
      pool.query("SELECT COUNT(*)::int AS open FROM network_incidents WHERE company_id=$1 AND status NOT IN ('resolved','closed')",[companyId]),
      pool.query("SELECT COUNT(*)::int AS upcoming FROM network_maintenance WHERE company_id=$1 AND status='planned' AND scheduled_for<=CURRENT_TIMESTAMP+INTERVAL '30 days'",[companyId]),
      pool.query(`SELECT COUNT(*)::int AS total FROM (SELECT ip_address FROM network_devices WHERE company_id=$1 AND ip_address<>'' GROUP BY ip_address HAVING COUNT(*)>1) x`,[companyId])]);
      res.json({devices:devices.rows[0],incidents:incidents.rows[0],maintenance:maintenance.rows[0],ip_conflicts:conflicts.rows[0].total});
    }catch(error){console.error("network dashboard:",error);res.status(500).json({error:"Erreur tableau de bord réseau."});}
  });

  router.get("/network/sites",authenticateToken,perm("reseau.sites","view"),async(req,res)=>{try{res.json((await pool.query("SELECT * FROM network_sites WHERE company_id=$1 ORDER BY name",[companyOf(req)])).rows);}catch{res.status(500).json({error:"Erreur lecture sites."});}});
  router.post("/network/sites",authenticateToken,perm("reseau.sites","create"),async(req,res)=>{try{const b=req.body||{},companyId=companyOf(req);if(!text(b.name)||!text(b.code))return res.status(400).json({error:"Code et nom obligatoires."});if(b.warehouse_id&&!(await owned("warehouses",b.warehouse_id,companyId)))return res.status(400).json({error:"Site MaliLink invalide."});const row=(await pool.query(`INSERT INTO network_sites
      (company_id,tenant_id,warehouse_id,code,name,address,responsible_name,status) VALUES ($1,$2,$3,$4,$5,$6,$7,'active') RETURNING *`,[companyId,tenantOf(req),b.warehouse_id||null,text(b.code,80),text(b.name),text(b.address,1000),text(b.responsible_name)])).rows[0];await audit(req,"create","site",row.id);res.status(201).json(row);}catch(error){res.status(error.code==="23505"?409:500).json({error:error.code==="23505"?"Ce code de site existe déjà.":"Erreur création site."});}});

  router.get("/network/devices",authenticateToken,perm("reseau.equipements","view"),async(req,res)=>{try{const q=`%${text(req.query.q,120)}%`;const rows=(await pool.query(`SELECT d.*,s.name AS site_name FROM network_devices d LEFT JOIN network_sites s ON s.id=d.site_id AND s.company_id=d.company_id
      WHERE d.company_id=$1 AND ($2='%%' OR d.name ILIKE $2 OR d.ip_address ILIKE $2 OR d.mac_address ILIKE $2 OR d.serial_number ILIKE $2)
      ORDER BY d.name LIMIT 1000`,[companyOf(req),q])).rows;res.json(rows);}catch{res.status(500).json({error:"Erreur lecture équipements."});}});

  router.post("/network/devices",authenticateToken,perm("reseau.equipements","create"),async(req,res)=>{try{const b=req.body||{},companyId=companyOf(req),category=text(b.category,60);if(!text(b.name)||!CATEGORIES.has(category))return res.status(400).json({error:"Nom et catégorie valide obligatoires."});if(b.site_id&&!(await owned("network_sites",b.site_id,companyId)))return res.status(400).json({error:"Site invalide."});const mac=text(b.mac_address,32).toLowerCase();if(mac&&!MAC.test(mac))return res.status(400).json({error:"Adresse MAC invalide."});const row=(await pool.query(`INSERT INTO network_devices
      (company_id,tenant_id,site_id,name,category,manufacturer,model,serial_number,ip_address,mac_address,vlan,ssid,switch_port,rack_location,firmware_version,installed_on,warranty_until,supplier,status,monitoring_type,monitoring_port,notes,created_by)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'unknown',$19,$20,$21,$22) RETURNING *`,[companyId,tenantOf(req),b.site_id||null,text(b.name),category,text(b.manufacturer),text(b.model),text(b.serial_number,180),text(b.ip_address,80),mac,text(b.vlan,80),text(b.ssid,180),text(b.switch_port,80),text(b.rack_location,160),text(b.firmware_version,120),b.installed_on||null,b.warranty_until||null,text(b.supplier),text(b.monitoring_type,30)||"none",b.monitoring_port?Number(b.monitoring_port):null,text(b.notes,3000),req.user.id])).rows[0];await audit(req,"create","device",row.id);res.status(201).json(row);}catch(error){res.status(error.code==="23505"?409:500).json({error:error.code==="23505"?"Numéro de série déjà utilisé dans cette société.":"Erreur création équipement."});}});

  router.put("/network/devices/:id",authenticateToken,perm("reseau.equipements","update"),async(req,res)=>{try{const companyId=companyOf(req),b=req.body||{};if(!(await owned("network_devices",req.params.id,companyId)))return res.status(404).json({error:"Équipement introuvable."});if(b.site_id&&!(await owned("network_sites",b.site_id,companyId)))return res.status(400).json({error:"Site invalide."});const mac=text(b.mac_address,32).toLowerCase();if(mac&&!MAC.test(mac))return res.status(400).json({error:"Adresse MAC invalide."});const row=(await pool.query(`UPDATE network_devices SET site_id=$1,name=$2,category=$3,manufacturer=$4,model=$5,serial_number=$6,ip_address=$7,mac_address=$8,vlan=$9,ssid=$10,switch_port=$11,rack_location=$12,firmware_version=$13,installed_on=$14,warranty_until=$15,supplier=$16,monitoring_type=$17,monitoring_port=$18,notes=$19,updated_at=CURRENT_TIMESTAMP WHERE id=$20 AND company_id=$21 RETURNING *`,[b.site_id||null,text(b.name),CATEGORIES.has(text(b.category,60))?text(b.category,60):"other",text(b.manufacturer),text(b.model),text(b.serial_number,180),text(b.ip_address,80),mac,text(b.vlan,80),text(b.ssid,180),text(b.switch_port,80),text(b.rack_location,160),text(b.firmware_version,120),b.installed_on||null,b.warranty_until||null,text(b.supplier),text(b.monitoring_type,30)||"none",b.monitoring_port?Number(b.monitoring_port):null,text(b.notes,3000),Number(req.params.id),companyId])).rows[0];await audit(req,"update","device",row.id);res.json(row);}catch{res.status(500).json({error:"Erreur modification équipement."});}});

  router.post("/network/devices/:id/check",authenticateToken,perm("reseau.supervision","update"),async(req,res)=>{try{const companyId=companyOf(req),device=await owned("network_devices",req.params.id,companyId);if(!device)return res.status(404).json({error:"Équipement introuvable."});if(!["http","https"].includes(device.monitoring_type))return res.status(409).json({error:"Aucune sonde HTTP/HTTPS sûre n’est configurée. L’état reste inconnu.",code:"PROBE_NOT_CONFIGURED"});if(!probe.debitAutorise(companyId))return res.status(429).json({error:"Limite de tests atteinte."});const target=await probe.verifierCible(device.ip_address,device.monitoring_port|| (device.monitoring_type==="https"?443:80));if(!target.ok)return res.status(409).json({error:target.message,code:target.code});const result=await probe.connexionTcp(target.adresse,target.port);const status=result.joignable?"online":"offline";await pool.query(`UPDATE network_devices SET status=$1,last_checked_at=CURRENT_TIMESTAMP,last_seen_at=CASE WHEN $1='online' THEN CURRENT_TIMESTAMP ELSE last_seen_at END,last_check_error=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$3 AND company_id=$4`,[status,result.erreur||"",device.id,companyId]);await audit(req,"check","device",device.id,`${status} ${result.duree_ms}ms`);res.json({status,duration_ms:result.duree_ms,precision:"Test TCP uniquement : il ne confirme pas le fonctionnement complet de l’équipement."});}catch(error){res.status(500).json({error:"Test réseau impossible."});}});

  router.get("/network/conflicts",authenticateToken,perm("reseau.adresses","view"),async(req,res)=>{try{const rows=(await pool.query(`SELECT ip_address,COUNT(*)::int AS count,json_agg(json_build_object('id',id,'name',name,'mac_address',mac_address)) AS devices FROM network_devices WHERE company_id=$1 AND ip_address<>'' GROUP BY ip_address HAVING COUNT(*)>1 ORDER BY ip_address`,[companyOf(req)])).rows;res.json(rows);}catch{res.status(500).json({error:"Erreur détection conflits."});}});

  router.get("/network/incidents",authenticateToken,perm("reseau.incidents","view"),async(req,res)=>{try{res.json((await pool.query(`SELECT i.*,d.name AS device_name,s.name AS site_name FROM network_incidents i LEFT JOIN network_devices d ON d.id=i.device_id AND d.company_id=i.company_id LEFT JOIN network_sites s ON s.id=i.site_id AND s.company_id=i.company_id WHERE i.company_id=$1 ORDER BY i.opened_at DESC`,[companyOf(req)])).rows);}catch{res.status(500).json({error:"Erreur lecture incidents."});}});
  router.post("/network/incidents",authenticateToken,perm("reseau.incidents","create"),async(req,res)=>{try{const b=req.body||{},companyId=companyOf(req);if(!text(b.title))return res.status(400).json({error:"Titre obligatoire."});if(b.device_id&&!(await owned("network_devices",b.device_id,companyId)))return res.status(400).json({error:"Équipement invalide."});if(b.site_id&&!(await owned("network_sites",b.site_id,companyId)))return res.status(400).json({error:"Site invalide."});if(b.assigned_to&&!(await owned("users",b.assigned_to,companyId)))return res.status(400).json({error:"Responsable invalide."});const row=(await pool.query(`INSERT INTO network_incidents (company_id,tenant_id,site_id,device_id,title,description,severity,status,assigned_to,opened_by) VALUES ($1,$2,$3,$4,$5,$6,$7,'open',$8,$9) RETURNING *`,[companyId,tenantOf(req),b.site_id||null,b.device_id||null,text(b.title),text(b.description,4000),text(b.severity,30)||"medium",b.assigned_to||null,req.user.id])).rows[0];await audit(req,"create","incident",row.id);res.status(201).json(row);}catch{res.status(500).json({error:"Erreur création incident."});}});

  router.get("/network/maintenance",authenticateToken,perm("reseau.maintenance","view"),async(req,res)=>{try{res.json((await pool.query(`SELECT m.*,d.name AS device_name FROM network_maintenance m LEFT JOIN network_devices d ON d.id=m.device_id AND d.company_id=m.company_id WHERE m.company_id=$1 ORDER BY m.scheduled_for NULLS LAST`,[companyOf(req)])).rows);}catch{res.status(500).json({error:"Erreur lecture maintenance."});}});
  router.post("/network/maintenance",authenticateToken,perm("reseau.maintenance","create"),async(req,res)=>{try{const b=req.body||{},companyId=companyOf(req);if(!b.device_id||!(await owned("network_devices",b.device_id,companyId)))return res.status(400).json({error:"Équipement valide obligatoire."});if(b.responsible_id&&!(await owned("users",b.responsible_id,companyId)))return res.status(400).json({error:"Responsable invalide."});const row=(await pool.query(`INSERT INTO network_maintenance (company_id,tenant_id,device_id,maintenance_type,scheduled_for,status,description,parts_used,cost,responsible_id,created_by) VALUES ($1,$2,$3,$4,$5,'planned',$6,$7,$8,$9,$10) RETURNING *`,[companyId,tenantOf(req),b.device_id,text(b.maintenance_type,80)||"preventive",b.scheduled_for||null,text(b.description,4000),text(b.parts_used,2000),Number(b.cost||0),b.responsible_id||null,req.user.id])).rows[0];await audit(req,"create","maintenance",row.id);res.status(201).json(row);}catch{res.status(500).json({error:"Erreur création maintenance."});}});

  return router;
};
